DROP TABLE IF EXISTS compilations CASCADE;

CREATE TABLE IF NOT EXISTS compilations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned              BOOLEAN NOT NULL,
    title               TEXT
);

DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE IF NOT EXISTS categories (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(50) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS locations CASCADE;

CREATE TABLE IF NOT EXISTS locations (
    id  BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat NUMERIC NOT NULL,
    lon NUMERIC NOT NULL
);

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(254) NOT NULL,
    email VARCHAR(254) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS events (
    id  BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation TEXT NOT NULL,
    category BIGINT NOT NULL,
    description TEXT NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    location BIGINT NOT NULL,
    initiator BIGINT NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INT NOT NULL,
    request_moderation BOOLEAN NOT NULL,
    confirmed_requests INT,
    title TEXT NOT NULL,
    state VARCHAR(10),
    views BIGINT DEFAULT 0,

    CONSTRAINT fk_on_category FOREIGN KEY (category) REFERENCES categories (id),
    CONSTRAINT fk_on_location FOREIGN KEY (location) REFERENCES locations (id),
    CONSTRAINT fk_on_user FOREIGN KEY (initiator) REFERENCES users (id)
);

DROP TABLE IF EXISTS compilation_to_events CASCADE;

CREATE TABLE IF NOT EXISTS compilation_to_events (
    compilation_id      BIGINT NOT NULL,
    event_id            BIGINT NOT NULL,

    CONSTRAINT pk_compilation_to_events PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_on_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id),
    CONSTRAINT fk_on_event FOREIGN KEY (event_id) REFERENCES events (id)
);

DROP TABLE IF EXISTS requests CASCADE;

CREATE TABLE IF NOT EXISTS requests (
    id  BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event BIGINT NOT NULL,
    requester BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT fk_event FOREIGN KEY (event) REFERENCES events (id),
    CONSTRAINT fk_on_requester FOREIGN KEY (requester) REFERENCES users (id)
);

DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS comments (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(3000) NOT NULL,
    author_id BIGINT REFERENCES users(id) NOT NULL,
    event_id  BIGINT REFERENCES events(id) NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    edited    TIMESTAMP WITHOUT TIME ZONE,

    CONSTRAINT fk_on_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES events (id)
);
