DROP TABLE IF EXISTS hits CASCADE;

CREATE TABLE IF NOT EXISTS hits (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app        VARCHAR(255) NOT NULL,
    uri        VARCHAR(500) NOT NULL,
    ip         VARCHAR(45) NOT NULL,
    hit_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_hits_ip ON hits(ip);
CREATE INDEX IF NOT EXISTS idx_hits_time ON hits(hit_time);
CREATE INDEX IF NOT EXISTS idx_hits_uri ON hits(uri);
CREATE INDEX IF NOT EXISTS idx_hits_app_time ON hits(app, hit_time);