spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: category_service_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**, /categories/**

        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**, /comments/**

        - id: compilation_service_route
          uri: lb://compilation-service
          predicates:
            - Path=/admin/compilations/**, /compilations/**

        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**, /events/**, /users/*/events, /users/*/events/**

        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**, /request/**

        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**, /users/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    gateway:
      enabled: true
      show-details: always

server:
  port: 8080