spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: category_service_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/*
            - Path=/admin/categories
            - Path=/categories/**
        - id: comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**
            - Path=/comments/**
        - id: compilation_service_route
          uri: lb://compilation-service
          predicates:
            - Path=/admin/compilations/**
            - Path=/compilations/**
        - id: event_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**
            - Path=/events/**
            - Path=/users/*/events
        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**
            - Path=/events/**
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    gateway:
      enabled: true
      show-details: always

server:
  port: 8080