DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS events (
    id  BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation TEXT NOT NULL,
    category BIGINT NOT NULL,
    description TEXT NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    location BIGINT NOT NULL,
    initiator BIGINT NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INT NOT NULL,
    request_moderation BOOLEAN NOT NULL,
    confirmed_requests INT,
    title TEXT NOT NULL,
    state VARCHAR(10),
    rating DECIMAL(10, 2) DEFAULT 0
);

DROP TABLE IF EXISTS locations CASCADE;

CREATE TABLE IF NOT EXISTS locations (
    id  BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat NUMERIC NOT NULL,
    lon NUMERIC NOT NULL
);

DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE IF NOT EXISTS comments (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(3000) NOT NULL,
    author_id BIGINT NOT NULL,
    event_id  BIGINT NOT NULL,
    created   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    edited    TIMESTAMP WITHOUT TIME ZONE
);

DROP TABLE IF EXISTS compilations CASCADE;

CREATE TABLE IF NOT EXISTS compilations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned              BOOLEAN NOT NULL,
    title               TEXT
);

CREATE TABLE IF NOT EXISTS compilation_to_events (
    compilation_id      BIGINT NOT NULL,
    event_id            BIGINT NOT NULL,

    CONSTRAINT pk_compilation_to_events PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_on_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);

CREATE TABLE IF NOT EXISTS categories (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(50) UNIQUE NOT NULL
);