DROP TABLE IF EXISTS compilations CASCADE;

CREATE TABLE IF NOT EXISTS compilations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned              BOOLEAN NOT NULL,
    title               TEXT
);

CREATE TABLE IF NOT EXISTS compilation_to_events (
    compilation_id      BIGINT NOT NULL,
    event_id            BIGINT NOT NULL,

    CONSTRAINT pk_compilation_to_events PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT fk_on_compilation FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);
