spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/main-service/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    gateway:
      enabled: true
      show-details: always

server:
  port: 8080